### ISSUE TITLE
GET Limitar quantidade de members como resposta

### ISSUE THREAD

**Issue by yubathom** [SPURB/consultas-publicas-backend#5]
Criar request do tipo get que aceite parâmetros para ordenar e limitar os comentários. Exemplo: `apiconsultas.php/members/10` (retorna os dez últimos members) e `apiconsultas.php/members/10/1` (retorna do 11 ao 20 member). @hsolucas

**Comment by hsolucas** [comment]
Em produção

**Comment by hsolucas** [comment]
Testar com pagedmembers/numerodapagina
