### ISSUE TITLE
GET /consultas

### ISSUE THREAD

**Issue by yubathom** [SPURB/consultas-publicas-backend#8]
alterar resposta de endpoint GET /consultas para padrão abaixo
```
{
    "id": numero,
    "nome": string,
    "ativo": boolean,
    "dataCadastro": 0000-00-00,
    “nomePublico”: string, 
    "dataFinal": 0000-00-00,
    "nContribuicoes": número,
    "textoIntro": string,
    "urlConsulta": string,
    "urlCapa": string
}
```
sendo que `id`, `nome`, `ativo`, `dataCadastro` já existem. `nomePublico`, `dataFinal`, `textoIntro`, `urlConsulta` e `urlCapa` serão colunas a serem criadas. 

`nContribuicoes` se refere a uma querie em mebers `select count(*) from members where id_consulta=X and public=1`. 

Vou passar um dump com as novas colunas para testar estas alterações.

**Comment by hsolucas** [comment]
Alterado. Favor homologar.

**Comment by yubathom** [comment]
Falta na resposta o item "nContribuicoes"

**Comment by yubathom** [comment]
Homologado localmente

**Comment by yubathom** [comment]
Incluir mais um item `urlDevolutiva`. Guardei querie para criar a coluna localmente:
```
ALTER TABLE `consultas` ADD `url_devolutiva` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL ;
````

novo item na resposta:
`urlDevolutiva: string`

**Comment by yubathom** [comment]
Testado e funcionando em produção

**Comment by yubathom** [comment]
Falta na resporta
`urlDevolutiva: string`

Favor fazer a atualização na branch "participe".

**Comment by yubathom** [comment]
Testado e validado em homologação
